### ISSUE TITLE
crash upon server start

### ISSUE THREAD

**Issue by ghost** [matcracker/BedcoreProtect#11]
### Issue description

- Expected result: plugin to work
- Actual result: crashed the server every time it starts

### Steps to reproduce the issue
1. download latest phar from poggit (144)
2. put it in plugins folder 

### OS and versions

* BedcoreProtect:  if i do /core status it gives me this error (```matcracker\BedcoreProtect\libs\SOFe\AwaitGenerator\AwaitException: "Unhandled async exception" (EXCEPTION) in "plugins/BedcoreProtect_dev-144.phar/src/matcracker/BedcoreProtect/libs/SOFe/AwaitGenerator/Await" at line 358```) but the version is the compiled #144 phar from poggit

* PocketMine-MP: 3.9.1 protocol 361
* PHP: 7.2
* Server OS: windows
* Game version: PE/Win10 (delete as appropriate)

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files

```ErrorException: "yaml_parse(): end of stream reached without finding document 0" (EXCEPTION) in "plugins/BedcoreProtect_dev-144.phar/src/matcracker/BedcoreProtect/storage/PatchManager" at line 43 ```

**Comment by matcracker** [comment]
Did you encountered this issue by running the plugin the first time or by upgrading it from a previous version?

**Comment by ghost** [comment]
from the first time

**Comment by ghost** [comment]
ohh btw i forgot to say that when i put this plugin in a private phone hosted server it worked fine but when i do /core status i get kicked with internal server error and this error shows up in the console ```(matcracker\BedcoreProtect\libs\SOFe\AwaitGenerator\AwaitException: "Unhandled async exception" (EXCEPTION) in "plugins/BedcoreProtect_dev-144.phar/src/matcracker/BedcoreProtect/libs/SOFe/AwaitGenerator/Await" at line 358``` 

but when i put it in my public server which is web hosted it never worked it crashes upon server starts as i pointed above.

**Comment by matcracker** [comment]
Thank you for you report, issue is fixed in v0.5.2 (alias [dev build #145](https://poggit.pmmp.io/ci/matcracker/BedcoreProtect/BedcoreProtect/dev:145))

**Comment by ghost** [comment]
issue still persists, the server freezes when the plugin disables itself with the same error:
```ErrorException: "yaml_parse(): end of stream reached without finding document 0" (EXCEPTION) in "plugins/BedcoreProtect_dev-145.phar/src/matcracker/BedcoreProtect/storage/PatchManager" at line 43
2019-10-05 [08:20:36] [Server thread/DEBUG]: #0 (): pocketmine\utils\Utils::errorExceptionHandler(integer 2, string[62] yaml_parse(): end of stream reached without finding document 0, string[144] phar:///home/minecraft/multicraft/servers/server22957/plugins/BedcoreProtect_dev, integer 43, array[2])
2019-10-05 [08:20:36] [Server thread/DEBUG]: #1 plugins/BedcoreProtect_dev-145.phar/src/matcracker/BedcoreProtect/storage/PatchManager(43): yaml_parse(string[30] # !!! DON'T EDIT THIS FILE !!!)
2019-10-05 [08:20:36] [Server thread/DEBUG]: #2 plugins/BedcoreProtect_dev-145.phar/src/matcracker/BedcoreProtect/storage/PatchManager(58): matcracker\BedcoreProtect\storage\PatchManager->getVersionsToPatch(string[5] 0.5.2)
2019-10-05 [08:20:36] [Server thread/DEBUG]: #3 plugins/BedcoreProtect_dev-145.phar/src/matcracker/BedcoreProtect/libs/poggit/libasynql/base/DataConnectorImpl(153): matcracker\BedcoreProtect\storage\PatchManager->matcracker\BedcoreProtect\storage\{closure}(array[1], array[3])
2019-10-05 [08:20:36] [Server thread/DEBUG]: #4 plugins/BedcoreProtect_dev-145.phar/src/matcracker/BedcoreProtect/libs/poggit/libasynql/base/DataConnectorImpl(183): matcracker\BedcoreProtect\libs\poggit\libasynql\base\DataConnectorImpl->matcracker\BedcoreProtect\libs\poggit\libasynql\base\{closure}(object matcracker\BedcoreProtect\libs\poggit\libasynql\result\SqlSelectResult)
2019-10-05 [08:20:36] [Server thread/DEBUG]: #5 plugins/BedcoreProtect_dev-145.phar/src/matcracker/BedcoreProtect/libs/poggit/libasynql/base/SqlThreadPool(91): matcracker\BedcoreProtect\libs\poggit\libasynql\base\DataConnectorImpl->matcracker\BedcoreProtect\libs\poggit\libasynql\base\{closure}(object matcracker\BedcoreProtect\libs\poggit\libasynql\result\SqlSelectResult)
2019-10-05 [08:20:36] [Server thread/DEBUG]: #6 plugins/BedcoreProtect_dev-145.phar/src/matcracker/BedcoreProtect/libs/poggit/libasynql/base/DataConnectorImpl(262): matcracker\BedcoreProtect\libs\poggit\libasynql\base\SqlThreadPool->readResults(array[1])
2019-10-05 [08:20:36] [Server thread/DEBUG]: #7 plugins/BedcoreProtect_dev-145.phar/src/matcracker/BedcoreProtect/libs/poggit/libasynql/base/DataConnectorImpl(256): matcracker\BedcoreProtect\libs\poggit\libasynql\base\DataConnectorImpl->checkResults()
2019-10-05 [08:20:36] [Server thread/DEBUG]: #8 plugins/BedcoreProtect_dev-145.phar/src/matcracker/BedcoreProtect/storage/PatchManager(71): matcracker\BedcoreProtect\libs\poggit\libasynql\base\DataConnectorImpl->waitAll()
2019-10-05 [08:20:36] [Server thread/DEBUG]: #9 plugins/BedcoreProtect_dev-145.phar/src/matcracker/BedcoreProtect/Main(150): matcracker\BedcoreProtect\storage\PatchManager->patch()
2019-10-05 [08:20:36] [Server thread/DEBUG]: #10 src/pocketmine/plugin/PluginBase(123): matcracker\BedcoreProtect\Main->onEnable()
2019-10-05 [08:20:36] [Server thread/DEBUG]: #11 src/pocketmine/plugin/PluginManager(588): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
2019-10-05 [08:20:36] [Server thread/DEBUG]: #12 src/pocketmine/Server(2002): pocketmine\plugin\PluginManager->enablePlugin(object matcracker\BedcoreProtect\Main)
2019-10-05 [08:20:36] [Server thread/DEBUG]: #13 src/pocketmine/Server(1988): pocketmine\Server->enablePlugin(object matcracker\BedcoreProtect\Main)
2019-10-05 [08:20:36] [Server thread/DEBUG]: #14 src/pocketmine/Server(1782): pocketmine\Server->enablePlugins(integer 1)
2019-10-05 [08:20:36] [Server thread/DEBUG]: #15 src/pocketmine/PocketMine(274): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[47] /home/minecraft/multicraft/servers/server22957/, string[55] /home/minecraft/multicraft/servers/server22957/plugins/)
2019-10-05 [08:20:36] [Server thread/DEBUG]: #16 (1): require(string[118] phar:///home/minecraft/multicraft/jar/versions/PocketMine/PocketMine-MP1.12.0-3.)
2019-10-05 [08:20:36] [Server thread/INFO]: Disabling BedcoreProtect v0.5.2```

**Comment by matcracker** [comment]
I can't reproduce the issue

**Comment by ghost** [comment]
it works fine on the phone hosted server but in the web hosted one it doesn't! thats so weird, i tried to add other plugins and they worked just fine

**Comment by ghost** [comment]
btw if this would make any help after the plugin disables itself and the server freezes the plugin data is created successfully:
- bedcore_database.db
- config.yml

**Comment by ghost** [comment]
if this issue is related to a not very important feature like for example an auto updater or update notifier it would be great if u tell me how to remove it so i can use this plugin

**Comment by matcracker** [comment]
@mote166 try to use build #146

**Comment by ghost** [comment]
worked! thanks.
